chore: snaps-cli 3.0.0
ChainSafe/metamask-snap-polkadot pull request #192
Opened 2023-10-09 11:01 UTC by irubido

2024-07-30 03:44 UTC, Rachale43 commented
Nope

2024-07-30 03:47 UTC, Rachale43 approved these changes

2024-07-30 03:49 UTC, Rachale43 requested changes
[]()

2024-07-30 03:50 UTC, Rachale43 commented
> []()

- [ ] -

2024-07-30 03:58 UTC, Rachale43 commented on packages/snap/snap.config.js
> -    outfileName: "bundle.js",
No

2024-08-27 14:06 UTC, Lykhoyda commented
@irubido I think it could be closed as the CLI was already updated in another PR

2024-08-27 14:06 UTC, closed without merging